spring:
  kafka:
    producer:
      bootstrapServers: kafka:9092
      acks: -1
      compressionType: lz4
      batchSize: 1
      bufferMemory: 10485760
      retries: 3
      topic: promo_available

mongo:
  password: '{cipher}{key:development}AgBjRz4vRd+s4BhXi8fiJF1SL2M0LWMOpiCh8gTSNq+m2wvTGbrF8ISXRplBTibcQduadQnZQhCh3U4c0v2ZwajVsIMXogTpuJWnz2z1s35lakowXMZqSqARn2QRTIEh2KI94B9d6B9AXlK0+Afp2pk2+1qjCz4YG4RiwB+b3vdYFz9+Aq683LEy5fHuTbXGedQrO5evXRv85Qx0ERnyaRyG2aw+Vrd1qSaxFb6TQRcadBvNbDv3z9r9T1iFcXKfbtrTq2QgddMWfGBx3IXpSDQND311kIcv5wCZsbOgp+Sejrd7cXmwhwNyLUEtT9/oHktd6dEvZsEJefzwY7AylRr6mwmRa+lFK0mZXHHPB3HP7K558GrSLsl9QF/4NEZByniK/MNOU3f8ULbEK+EIgkDYTvsziqL5XYopeddODG8FmBLSR7k51Ut9A5ZiTY/sX2w+B2rCQfH7V8GmordhlZ3o/GW+waL1Rx006h5mBa011k03qSkvZE9AXXN63n+gb+Lognh3k5LhymnF4xFCY7wC1O2EJMLyAAUUKHEhjXhgduSAR4VaZ/5z1xMyeBup39nhgW6NqitOywdG9wCmXkr4b8yBupKLas1daa9vsRC0aFjK1l+or9h+fkRwqzB5fA6rdzbHHY9NQ3FOdA7KkzkjnfSDcMXllK394gF/2jfuj0o5OqUhKCbA0UourJHDXqHJvN9PhoPSLOaduBLH+P5H'
  config:
    uri: mongodb://promoManager:${mongo.password}@mongodb:27017/promoManager
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /promoManager/v1
