spring:
  kafka:
    producer:
      bootstrapServers: kafka:9092
      acks: -1
      compressionType: lz4
      batchSize: 1
      bufferMemory: 10485760
      retries: 3
      topic: promo_available

mongo:
  password: '{cipher}{key:default}AgB9w0ar4m+nIee5+1cHGsc2N654UeBbfg0Mn1SIcoBQHxhPSFcIY7YPblcMAs045MrQrJwY1tx98eKkjsYL0sXkytxV0aA8TmluOdJFnH5jgGmRTIOc2StCEFqbmXZo07JkZqfRKLk3yMGFjZG4aLI9YZQ9pwdsz+DrSqqpPRzOXaBsdYVW+2KXNaKiii3m6QHRblS9uEs5GzBqkExy1+3W4e0tDaYHCSbXNy1rXcwW9Mnja1ZJE+kn8NM4qTB7SsN/3tgrJB+qx19p2Z6404RxFWFW0o68IZv8kZX659G0VLxi2cdIx1ZUpoqva55Gv45t599teZKvCwxPTXM4GWHuxD1fcNJ0zjMUz5vDZTyAJoiBfU4zBeB6v6sn+kvA4m7U/tg+KyTx9Xc1KKst50ANV0HLfGX5GaCSBo3xfB5m8U3uBPr7SowGYcEN+cXpaY0jRkAbiEmO3fU66+GIfNgV8BBMeY949QN2om8XnpHqpF7Adytaa7eUriEQWCiiZN+fWB20u8Rkk8PJXTZVtTJtUlImaelvL8eNgJkX0F0zhVTA4tiIo9fApuNXk+/GmZa2atAtoYa05vRc5hFOqEKOMv8q5uU+QBRlIVXA+BQZNQBZbrdxXhxEcy2fggVk4a4wvAs2y1tjWV5q+C1ySAY43Xt56oeUl3iSdbeaGUMzlCxt+eb0KYRSNd4C6pNpy8iimKbUg2xfJe+CAg3zwKY+'
  config:
    uri: mongodb://promoManager:${mongo.password}@mongodb:27017/promoManager
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /
