spring:
  kafka:
    producer:
      bootstrapServers: kafka:9092
      acks: -1
      compressionType: lz4
      batchSize: 1
      bufferMemory: 10485760
      retries: 3
      topic: promo_available

mongo:
#  password:
  config:
    uri: mongodb://promoManager:password@mongodb:27017/promoManager
    replicaSetName: '{cipher}AgCMi1g1fMUji+nxgNN7eyPW+5+0zQPbJ7ZDnIUx+/2+S7bl8v8Euf3CB3+1539TYoSoggkwXCwvrmpTDMRCCCi1a04JQ80fT8WNjGOPfSBDCuVv66ksWa9v/3P8Iv2SyKU6rawbSgwpShIZ66Svf6hmPE6tJqq6Ds87i8YAlhm9RSW8xEdZaZbih3JXiYPTYHByMcWl5viOOgNzwS3tEMhFsSGDpl4rMt8rcT9f4ZxgFIbWAQQGfpBOGbNbYr1/5Ao6EXZTjp4mZisowtYfXb2r4IGz2kLe9zd4Gdhqm4e3/be36UsKJ+SdzkSQO9Fz+dmttpJXHfKoiyP8Im5tM9ORSYPoPiMikHk4EQ4MeAxBDE8T3MDWaY/6JQ2GqGMlneJJabdqfKnwf9hfmAPOi56Y4LAEI2JT46GlCGVwnxL35kHDm2po1tcvAflZ0yTYBfldw8OH4AU/z+x7Zloy2yOSiXNlPKCkG6Q7kVEr8l3NmlyOblCjxZ1A6NKF6yDxpIQVsRw5ot6dsZX95gcb8kx2frbM7UsG0yRifbjQ21u+rTqZWlE1Rpm8xVdZ3YRJYT58t4Fx2ji6sacvcD8VBhrkhIMHeZf3Fb7w05oyP4RgkxIIszWhuqb6Ax9Okx+XWfjAhtMniNESZS8X+hy9MlYj+kUS0dcpTz7nc3mebgcGGFE4DEi+fMCtLAA+/kIS7SscfsjVMMjfqEyAWxjp846Q'
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /promoManager/v1
