spring:
  kafka:
    producer:
      bootstrapServers: kafka:9092
      acks: -1
      compressionType: lz4
      batchSize: 1
      bufferMemory: 10485760
      retries: 3
      topic: promo_available

mongo:
  password: '{cipher}AgCESmAF+usrDDkY93ybwAnCJ60+K9EpGeQd18EDTsZl6r7mzeshsI4/PixJPKTJ9x3cGFhb1RWGEYc3ICLAt2xFd9tmd9Lob+USVuICEsbScmKXFy1b4maFL5+n/xmLK/JScgNKnCV7163vHWZ+dqmryDc/eOYt4x2hWfk+AKktfqUkGLpVVo5C7PjMgMLpojZctia0qGNxZJEr/ukeGW//Aojj3fJzYGmDprje9jB5KWHqOD+GDu8tzNb1st0Z1NbNTO/x6yOtzIjcWh9Ldki/+GHl2j9/Vm+Gpz/suDjmvgEEZviDeC0zI+O1SB8hyECEiiD/HGE5qcxACA5LBA0khD15tcCdWDENo43azZLcMF9iuLM9qrGA+Ma+Q8htTXz5VvtHEaMgcg/CeE3oPpNi4LQ2xozjLm7pCk+UvHZiKFUKK72+XlIjcNqQvi/s1dd3+OPUwrE8RwalWi99L3Gc4n0ZNb+IuWS3JTRcjJUrB7zCkEcrhrsCgpZyGVyILqbG5dadiaTgdt3gMvdes9stofTXNoxDKAa3fBwF/KQUqan27Cbutbs6Gjtvpv5yi20WufbpV6arOidAkpmo0pkWDFFbPdRhkShe+FtoI+EaAyNVhsky7dn5WWuedmo1wTgaE4qLxXkEJh0DnkGiNQq5pddLXKqJF/rYTDfdOrxOJS7YeK/Lkud18EpRJzbS14I0UU3p+Tt+KwIi60uvtnQ7'
  config:
    uri: mongodb://promoManager:password@mongodb:27017/promoManager
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /promoManager/v1
