spring:
  kafka:
    producer:
      bootstrapServers: kafka:9092
      acks: -1
      compressionType: lz4
      batchSize: 1
      bufferMemory: 10485760
      retries: 3
      topic: promo_available

mongo:
  password: '{cipher}AQAQKHy047H8McoIa28nFsPhRzs5xEsT4JoP9JEUrwHTXse22yi5BXZMgK1hV5z8lJNI2DxYWW/gApXUxZA2Yo1H73iQo6rC4lzMLXPfH5b0bApomUPqjFN6u3pmywBSs+jmeS4j0xXTBSQ8SKxkAZrQPp8W8ANEOTu9Ww6DeUPvnkF/kaOJPxuatPKhDwJHEg2mS13idtQ7SKd022mTGTuhOTWNaWqtAbKLPlr9w+mW8z55kHcKKmRxJJbgtZvO321HONZM5g1nB1GfNsuITtkIg1cmfOp6AXwyykCaR4H/V6lRq3ywdodQm4W4ve1F8UCG+s2PNNfWXhUARCntfxDDhRAoD8EUu7KMGc9l4o4B1JPv3ZeGFp7W9XkVxNowHSA='
  config:
    uri: mongodb://promoManager:${mongo.password}@mongodb:27017/promoManager
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /promoManager/v1
